# Multilingual Sparse Baseline for BEA 2026

This notebook adds a PyTerrier-compatible multilingual sparse retrieval baseline using `opensearch-project/opensearch-neural-sparse-encoding-multilingual-v1` and reports results in the same style as Table 1.

In [1]:
import os
import re
import unicodedata
from pathlib import Path
from typing import List, Tuple

import faiss
import numpy as np
import pandas as pd
import pyterrier as pt
import torch
from sentence_transformers import SentenceTransformer, SparseEncoder, util

os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

_ws_re = re.compile(r"\s+")
_tags_re = re.compile(r"<[^>]+>")

def normalize_text(s: str) -> str:
    if s is None:
        return ""
    s = str(s)
    s = _tags_re.sub(" ", s)
    s = unicodedata.normalize("NFKC", s)
    s = s.lower()
    s = re.sub(r"[^0-9a-zA-ZäöüßÄÖÜẞ]+", " ", s)
    s = _ws_re.sub(" ", s).strip()
    return s

def safe_concat(parts):
    clean = []
    for p in parts:
        if p is None:
            continue
        p = str(p)
        if p.strip() in ("", "N/A", "nan"):
            continue
        clean.append(p)
    return " ".join(clean)

def build_doc_text(row: pd.Series) -> str:
    return safe_concat([row.get("question"), row.get("choices_processed")])

def ensure_run(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    if "qid" not in df.columns or "docno" not in df.columns:
        raise ValueError("Run must contain columns: qid, docno")
    df["qid"] = df["qid"].astype(str)
    df["docno"] = df["docno"].astype(str)
    if "score" not in df.columns:
        df["score"] = 0.0
    df["score"] = df["score"].astype(float)
    if "rank" not in df.columns:
        df = df.sort_values(["qid", "score"], ascending=[True, False])
        df["rank"] = df.groupby("qid").cumcount() + 1
    return df

if not pt.java.started():
    pt.java.init()

/Users/user/miniconda3/envs/KG-re-ranking/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Java started and loaded: pyterrier.java.colab, pyterrier.java, pyterrier.java.24, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]

In [2]:
PROJECT_ROOT = Path("/Users/user/Submissions/BEA-2026").resolve()
QB_PATH = PROJECT_ROOT / "qbank.csv"
QUERIES_PATH = PROJECT_ROOT / "queries.csv"
QRELS_PATH = PROJECT_ROOT / "qrels.tsv"

ART_DIR = PROJECT_ROOT / "artifacts" / "sparse_baseline"
ART_DIR.mkdir(parents=True, exist_ok=True)

DENSE_MODEL = "deutsche-telekom/gbert-large-paraphrase-cosine"
SPARSE_MODEL = "opensearch-project/opensearch-neural-sparse-encoding-multilingual-v1"
DENSE_TOPK = 100
FINAL_TOPK = 50

qb = pd.read_csv(QB_PATH).fillna("N/A")
queries = pd.read_csv(QUERIES_PATH).fillna("")
qrels = pd.read_csv(QRELS_PATH, sep="\t").fillna(0)

qb["docno"] = qb["test_item_id"].astype(str)
qb["raw_text"] = qb.apply(build_doc_text, axis=1)
qb["text"] = qb["raw_text"].map(normalize_text)
corpus = qb[["docno", "text"]].copy()

topics = queries.rename(columns={"queries": "query"})[["qid", "query"]].copy()
topics["qid"] = topics["qid"].astype(str)
topics["query"] = topics["query"].astype(str).map(normalize_text)

qrels = qrels.rename(columns={"rel": "label"})[["qid", "docno", "label"]].copy()
qrels["qid"] = qrels["qid"].astype(str)
qrels["docno"] = qrels["docno"].astype(str)
qrels["label"] = qrels["label"].astype(int)

print("corpus:", corpus.shape)
print("topics:", topics.shape)
print("qrels:", qrels.shape)

corpus: (2812, 2)
topics: (15, 2)
qrels: (2755, 3)

In [3]:
class FaissDenseRetriever(pt.Transformer):
    def __init__(self, corpus_df: pd.DataFrame, model_name: str, topk: int, show_progress: bool = True):
        super().__init__()
        self.topk = int(topk)
        cdf = corpus_df[["docno", "text"]].copy()
        cdf["docno"] = cdf["docno"].astype(str)
        cdf["text"] = cdf["text"].astype(str)
        self.docnos = cdf["docno"].tolist()
        self.st = SentenceTransformer(model_name, device="cpu")
        xdoc = self.st.encode(
            cdf["text"].tolist(),
            convert_to_numpy=True,
            normalize_embeddings=True,
            show_progress_bar=bool(show_progress),
        ).astype("float32")
        self.index = faiss.IndexFlatIP(xdoc.shape[1])
        self.index.add(xdoc)

    def transform(self, topics_df: pd.DataFrame) -> pd.DataFrame:
        qids = topics_df["qid"].astype(str).tolist()
        qs = topics_df["query"].astype(str).tolist()
        q = self.st.encode(qs, convert_to_numpy=True, normalize_embeddings=True, show_progress_bar=False).astype("float32")
        scores, idxs = self.index.search(q, self.topk)
        rows = []
        for i, qid in enumerate(qids):
            for rank, (j, sc) in enumerate(zip(idxs[i], scores[i]), start=1):
                if j < 0:
                    continue
                rows.append({"qid": qid, "docno": self.docnos[j], "score": float(sc), "rank": int(rank)})
        return pd.DataFrame(rows)

class SparseEncoderRetriever(pt.Transformer):
    def __init__(self, corpus_df: pd.DataFrame, model_name: str, topk: int = 50, batch_size: int = 16):
        super().__init__()
        cdf = corpus_df[["docno", "text"]].copy()
        cdf["docno"] = cdf["docno"].astype(str)
        cdf["text"] = cdf["text"].astype(str)
        self.docnos = cdf["docno"].tolist()
        self.topk = int(topk)
        self.batch_size = int(batch_size)
        self.model = SparseEncoder(model_name, device="cpu")
        self.doc_emb = self.model.encode_document(
            cdf["text"].tolist(),
            batch_size=self.batch_size,
            convert_to_tensor=True,
            show_progress_bar=True,
        )

    def transform(self, topics_df: pd.DataFrame) -> pd.DataFrame:
        qids = topics_df["qid"].astype(str).tolist()
        qs = topics_df["query"].astype(str).tolist()
        query_emb = self.model.encode_query(
            qs,
            batch_size=self.batch_size,
            convert_to_tensor=True,
            show_progress_bar=True,
        )
        scores = util.dot_score(query_emb, self.doc_emb)
        rows = []
        for qi, qid in enumerate(qids):
            top = torch.topk(scores[qi], k=self.topk)
            for rank, (score, idx) in enumerate(zip(top.values.tolist(), top.indices.tolist()), start=1):
                rows.append({"qid": qid, "docno": self.docnos[int(idx)], "score": float(score), "rank": int(rank)})
        return pd.DataFrame(rows)

def cut_k(k: int) -> pt.Transformer:
    return pt.apply.generic(lambda df: df.groupby("qid", sort=False).head(int(k)))

def eval_at_k(pipelines: List[Tuple[str, pt.Transformer]], topics_df: pd.DataFrame, qrels_df: pd.DataFrame, k_eval: int) -> pd.DataFrame:
    metrics = [
        f"ndcg_cut.{k_eval}",
        "recip_rank",
        f"P.{k_eval}",
        f"recall.{k_eval}",
        f"map_cut.{k_eval}",
    ]
    df = pt.Experiment(
        [p for _, p in pipelines],
        topics_df,
        qrels_df,
        eval_metrics=metrics,
        names=[n for n, _ in pipelines],
        verbose=True,
        validate="ignore",
    )
    df = df.rename(columns={
        f"ndcg_cut.{k_eval}": f"nDCG@{k_eval}",
        "recip_rank": f"MRR@{k_eval}",
        f"P.{k_eval}": f"Prec@{k_eval}",
        f"recall.{k_eval}": f"Recall@{k_eval}",
        f"map_cut.{k_eval}": f"MAP@{k_eval}",
    }).copy()
    p = df[f"Prec@{k_eval}"].astype(float)
    r = df[f"Recall@{k_eval}"].astype(float)
    df[f"F1@{k_eval}"] = np.where((p + r) > 0, 2 * p * r / (p + r), 0.0)
    cols = ["name", f"nDCG@{k_eval}", f"MRR@{k_eval}", f"Prec@{k_eval}", f"Recall@{k_eval}", f"F1@{k_eval}", f"MAP@{k_eval}"]
    return df[cols]

def to_table1_style(metrics_df: pd.DataFrame, ann_name: str, k_eval: int = 50) -> pd.DataFrame:
    df = metrics_df.copy()
    ann_ndcg = float(df.loc[df["name"] == ann_name, f"nDCG@{k_eval}"].iloc[0])
    df["Delta"] = df[f"nDCG@{k_eval}"].astype(float) - ann_ndcg
    df["Pct"] = np.where(ann_ndcg != 0, 100.0 * df["Delta"] / ann_ndcg, 0.0)
    out = pd.DataFrame({
        "Method": df["name"],
        "nDCG": df[f"nDCG@{k_eval}"].astype(float),
        "Delta": df["Delta"].astype(float),
        "%": df["Pct"].astype(float),
        "MRR": df[f"MRR@{k_eval}"].astype(float),
        "P": df[f"Prec@{k_eval}"].astype(float),
        "R": df[f"Recall@{k_eval}"].astype(float),
        "F1": df[f"F1@{k_eval}"].astype(float),
        "MAP": df[f"MAP@{k_eval}"].astype(float),
    })
    return out

In [4]:
dense100 = FaissDenseRetriever(corpus, model_name=DENSE_MODEL, topk=DENSE_TOPK)
sparse50 = SparseEncoderRetriever(corpus, model_name=SPARSE_MODEL, topk=FINAL_TOPK, batch_size=16)
cut50 = cut_k(FINAL_TOPK)

all_pipelines: List[Tuple[str, pt.Transformer]] = [
    ("ANN@100->@50", dense100 >> cut50),
    ("OpenSearch sparse encoder (multilingual)->@50", sparse50),
]

metrics_df = eval_at_k(all_pipelines, topics, qrels, k_eval=FINAL_TOPK)
metrics_df = metrics_df.sort_values(f"nDCG@{FINAL_TOPK}", ascending=False).reset_index(drop=True)
print(metrics_df.to_string(index=False))
metrics_df

Batches:   0%|          | 0/88 [00:00<?, ?it/s]

Batches:   1%|          | 1/88 [00:05<07:20,  5.06s/it]

Batches:   2%|▏         | 2/88 [00:09<06:57,  4.85s/it]

Batches:   3%|▎         | 3/88 [00:13<06:15,  4.42s/it]

Batches:   5%|▍         | 4/88 [00:17<05:57,  4.25s/it]

Batches:   6%|▌         | 5/88 [00:21<05:36,  4.06s/it]

Batches:   7%|▋         | 6/88 [00:25<05:21,  3.93s/it]

Batches:   8%|▊         | 7/88 [00:28<05:09,  3.82s/it]

Batches:   9%|▉         | 8/88 [00:31<04:50,  3.63s/it]

Batches:  10%|█         | 9/88 [00:35<04:40,  3.56s/it]

Batches:  11%|█▏        | 10/88 [00:38<04:28,  3.44s/it]

Batches:  12%|█▎        | 11/88 [00:41<04:20,  3.38s/it]

Batches:  14%|█▎        | 12/88 [00:44<04:12,  3.32s/it]

Batches:  15%|█▍        | 13/88 [00:48<04:08,  3.32s/it]

Batches:  16%|█▌        | 14/88 [00:51<04:01,  3.26s/it]

Batches:  17%|█▋        | 15/88 [00:54<03:47,  3.12s/it]

Batches:  18%|█▊        | 16/88 [00:56<03:37,  3.02s/it]

Batches:  19%|█▉        | 17/88 [01:00<03:37,  3.07s/it]

Batches:  20%|██        | 18/88 [01:02<03:24,  2.92s/it]

Batches:  22%|██▏       | 19/88 [01:05<03:17,  2.86s/it]

Batches:  23%|██▎       | 20/88 [01:08<03:09,  2.79s/it]

Batches:  24%|██▍       | 21/88 [01:10<03:04,  2.76s/it]

Batches:  25%|██▌       | 22/88 [01:13<02:57,  2.70s/it]

Batches:  26%|██▌       | 23/88 [01:15<02:50,  2.63s/it]

Batches:  27%|██▋       | 24/88 [01:18<02:44,  2.56s/it]

Batches:  28%|██▊       | 25/88 [01:20<02:35,  2.47s/it]

Batches:  30%|██▉       | 26/88 [01:22<02:32,  2.45s/it]

Batches:  31%|███       | 27/88 [01:25<02:28,  2.43s/it]

Batches:  32%|███▏      | 28/88 [01:27<02:20,  2.34s/it]

Batches:  33%|███▎      | 29/88 [01:29<02:15,  2.30s/it]

Batches:  34%|███▍      | 30/88 [01:31<02:14,  2.31s/it]

Batches:  35%|███▌      | 31/88 [01:34<02:11,  2.31s/it]

Batches:  36%|███▋      | 32/88 [01:36<02:06,  2.27s/it]

Batches:  38%|███▊      | 33/88 [01:38<02:04,  2.26s/it]

Batches:  39%|███▊      | 34/88 [01:40<02:00,  2.23s/it]

Batches:  40%|███▉      | 35/88 [01:42<01:52,  2.13s/it]

Batches:  41%|████      | 36/88 [01:44<01:51,  2.14s/it]

Batches:  42%|████▏     | 37/88 [01:46<01:46,  2.09s/it]

Batches:  43%|████▎     | 38/88 [01:48<01:41,  2.03s/it]

Batches:  44%|████▍     | 39/88 [01:50<01:40,  2.04s/it]

Batches:  45%|████▌     | 40/88 [01:52<01:39,  2.07s/it]

Batches:  47%|████▋     | 41/88 [01:54<01:34,  2.01s/it]

Batches:  48%|████▊     | 42/88 [01:56<01:34,  2.05s/it]

Batches:  49%|████▉     | 43/88 [01:58<01:29,  1.99s/it]

Batches:  50%|█████     | 44/88 [02:00<01:25,  1.94s/it]

Batches:  51%|█████     | 45/88 [02:02<01:22,  1.93s/it]

Batches:  52%|█████▏    | 46/88 [02:04<01:20,  1.91s/it]

Batches:  53%|█████▎    | 47/88 [02:06<01:16,  1.88s/it]

Batches:  55%|█████▍    | 48/88 [02:07<01:14,  1.87s/it]

Batches:  56%|█████▌    | 49/88 [02:09<01:12,  1.86s/it]

Batches:  57%|█████▋    | 50/88 [02:11<01:09,  1.84s/it]

Batches:  58%|█████▊    | 51/88 [02:13<01:08,  1.84s/it]

Batches:  59%|█████▉    | 52/88 [02:15<01:05,  1.81s/it]

Batches:  60%|██████    | 53/88 [02:16<01:03,  1.81s/it]

Batches:  61%|██████▏   | 54/88 [02:18<00:59,  1.76s/it]

Batches:  62%|██████▎   | 55/88 [02:20<00:57,  1.76s/it]

Batches:  64%|██████▎   | 56/88 [02:22<00:55,  1.74s/it]

Batches:  65%|██████▍   | 57/88 [02:23<00:54,  1.74s/it]

Batches:  66%|██████▌   | 58/88 [02:25<00:51,  1.70s/it]

Batches:  67%|██████▋   | 59/88 [02:27<00:50,  1.74s/it]

Batches:  68%|██████▊   | 60/88 [02:28<00:47,  1.71s/it]

Batches:  69%|██████▉   | 61/88 [02:30<00:45,  1.70s/it]

Batches:  70%|███████   | 62/88 [02:32<00:45,  1.74s/it]

Batches:  72%|███████▏  | 63/88 [02:34<00:43,  1.75s/it]

Batches:  73%|███████▎  | 64/88 [02:35<00:41,  1.72s/it]

Batches:  74%|███████▍  | 65/88 [02:37<00:40,  1.75s/it]

Batches:  75%|███████▌  | 66/88 [02:39<00:37,  1.72s/it]

Batches:  76%|███████▌  | 67/88 [02:40<00:35,  1.68s/it]

Batches:  77%|███████▋  | 68/88 [02:42<00:32,  1.61s/it]

Batches:  78%|███████▊  | 69/88 [02:43<00:29,  1.57s/it]

Batches:  80%|███████▉  | 70/88 [02:45<00:27,  1.52s/it]

Batches:  81%|████████  | 71/88 [02:47<00:27,  1.62s/it]

Batches:  82%|████████▏ | 72/88 [02:48<00:25,  1.62s/it]

Batches:  83%|████████▎ | 73/88 [02:50<00:23,  1.54s/it]

Batches:  84%|████████▍ | 74/88 [02:51<00:20,  1.49s/it]

Batches:  85%|████████▌ | 75/88 [02:52<00:18,  1.43s/it]

Batches:  86%|████████▋ | 76/88 [02:54<00:16,  1.39s/it]

Batches:  88%|████████▊ | 77/88 [02:55<00:15,  1.41s/it]

Batches:  89%|████████▊ | 78/88 [02:56<00:13,  1.38s/it]

Batches:  90%|████████▉ | 79/88 [02:58<00:12,  1.36s/it]

Batches:  91%|█████████ | 80/88 [02:59<00:10,  1.32s/it]

Batches:  92%|█████████▏| 81/88 [03:00<00:09,  1.31s/it]

Batches:  93%|█████████▎| 82/88 [03:01<00:07,  1.23s/it]

Batches:  94%|█████████▍| 83/88 [03:02<00:05,  1.19s/it]

Batches:  95%|█████████▌| 84/88 [03:03<00:04,  1.17s/it]

Batches:  97%|█████████▋| 85/88 [03:04<00:03,  1.12s/it]

Batches:  98%|█████████▊| 86/88 [03:05<00:02,  1.10s/it]

Batches:  99%|█████████▉| 87/88 [03:06<00:01,  1.03s/it]

Batches: 100%|██████████| 88/88 [03:07<00:00,  1.11it/s]

Batches: 100%|██████████| 88/88 [03:07<00:00,  2.13s/it]

Batches:   0%|          | 0/176 [00:00<?, ?it/s]

Batches:   1%|          | 1/176 [00:02<08:27,  2.90s/it]

Batches:   1%|          | 2/176 [00:04<06:35,  2.27s/it]

Batches:   2%|▏         | 3/176 [00:06<06:00,  2.08s/it]

Batches:   2%|▏         | 4/176 [00:08<05:29,  1.92s/it]

Batches:   3%|▎         | 5/176 [00:09<05:08,  1.81s/it]

Batches:   3%|▎         | 6/176 [00:11<04:50,  1.71s/it]

Batches:   4%|▍         | 7/176 [00:12<04:36,  1.64s/it]

Batches:   5%|▍         | 8/176 [00:14<04:28,  1.60s/it]

Batches:   5%|▌         | 9/176 [00:15<04:17,  1.54s/it]

Batches:   6%|▌         | 10/176 [00:17<04:09,  1.50s/it]

Batches:   6%|▋         | 11/176 [00:18<04:03,  1.48s/it]

Batches:   7%|▋         | 12/176 [00:20<04:06,  1.50s/it]

Batches:   7%|▋         | 13/176 [00:21<03:52,  1.43s/it]

Batches:   8%|▊         | 14/176 [00:22<03:45,  1.39s/it]

Batches:   9%|▊         | 15/176 [00:24<03:40,  1.37s/it]

Batches:   9%|▉         | 16/176 [00:25<03:35,  1.34s/it]

Batches:  10%|▉         | 17/176 [00:26<03:28,  1.31s/it]

Batches:  10%|█         | 18/176 [00:27<03:20,  1.27s/it]

Batches:  11%|█         | 19/176 [00:29<03:19,  1.27s/it]

Batches:  11%|█▏        | 20/176 [00:30<03:12,  1.23s/it]

Batches:  12%|█▏        | 21/176 [00:31<03:19,  1.29s/it]

Batches:  12%|█▎        | 22/176 [00:32<03:08,  1.23s/it]

Batches:  13%|█▎        | 23/176 [00:33<03:02,  1.19s/it]

Batches:  14%|█▎        | 24/176 [00:34<02:57,  1.17s/it]

Batches:  14%|█▍        | 25/176 [00:36<02:55,  1.16s/it]

Batches:  15%|█▍        | 26/176 [00:37<02:51,  1.14s/it]

Batches:  15%|█▌        | 27/176 [00:38<02:47,  1.12s/it]

Batches:  16%|█▌        | 28/176 [00:39<02:51,  1.16s/it]

Batches:  16%|█▋        | 29/176 [00:40<02:49,  1.15s/it]

Batches:  17%|█▋        | 30/176 [00:41<02:45,  1.13s/it]

Batches:  18%|█▊        | 31/176 [00:42<02:43,  1.13s/it]

Batches:  18%|█▊        | 32/176 [00:43<02:40,  1.11s/it]

Batches:  19%|█▉        | 33/176 [00:44<02:33,  1.07s/it]

Batches:  19%|█▉        | 34/176 [00:45<02:31,  1.07s/it]

Batches:  20%|█▉        | 35/176 [00:47<02:30,  1.07s/it]

Batches:  20%|██        | 36/176 [00:48<02:27,  1.05s/it]

Batches:  21%|██        | 37/176 [00:49<02:27,  1.06s/it]

Batches:  22%|██▏       | 38/176 [00:50<02:25,  1.06s/it]

Batches:  22%|██▏       | 39/176 [00:51<02:22,  1.04s/it]

Batches:  23%|██▎       | 40/176 [00:52<02:17,  1.01s/it]

Batches:  23%|██▎       | 41/176 [00:53<02:13,  1.01it/s]

Batches:  24%|██▍       | 42/176 [00:54<02:12,  1.01it/s]

Batches:  24%|██▍       | 43/176 [00:54<02:09,  1.03it/s]

Batches:  25%|██▌       | 44/176 [00:55<02:06,  1.04it/s]

Batches:  26%|██▌       | 45/176 [00:56<02:06,  1.03it/s]

Batches:  26%|██▌       | 46/176 [00:57<02:03,  1.06it/s]

Batches:  27%|██▋       | 47/176 [00:58<02:02,  1.05it/s]

Batches:  27%|██▋       | 48/176 [00:59<02:01,  1.05it/s]

Batches:  28%|██▊       | 49/176 [01:00<01:58,  1.08it/s]

Batches:  28%|██▊       | 50/176 [01:01<01:55,  1.09it/s]

Batches:  29%|██▉       | 51/176 [01:02<01:53,  1.10it/s]

Batches:  30%|██▉       | 52/176 [01:03<01:53,  1.09it/s]

Batches:  30%|███       | 53/176 [01:04<01:53,  1.08it/s]

Batches:  31%|███       | 54/176 [01:05<01:50,  1.11it/s]

Batches:  31%|███▏      | 55/176 [01:05<01:47,  1.13it/s]

Batches:  32%|███▏      | 56/176 [01:06<01:45,  1.13it/s]

Batches:  32%|███▏      | 57/176 [01:07<01:43,  1.15it/s]

Batches:  33%|███▎      | 58/176 [01:08<01:42,  1.15it/s]

Batches:  34%|███▎      | 59/176 [01:09<01:41,  1.15it/s]

Batches:  34%|███▍      | 60/176 [01:10<01:42,  1.14it/s]

Batches:  35%|███▍      | 61/176 [01:11<01:39,  1.16it/s]

Batches:  35%|███▌      | 62/176 [01:11<01:38,  1.16it/s]

Batches:  36%|███▌      | 63/176 [01:12<01:36,  1.18it/s]

Batches:  36%|███▋      | 64/176 [01:13<01:33,  1.20it/s]

Batches:  37%|███▋      | 65/176 [01:14<01:31,  1.21it/s]

Batches:  38%|███▊      | 66/176 [01:15<01:31,  1.20it/s]

Batches:  38%|███▊      | 67/176 [01:16<01:30,  1.20it/s]

Batches:  39%|███▊      | 68/176 [01:16<01:31,  1.19it/s]

Batches:  39%|███▉      | 69/176 [01:17<01:29,  1.20it/s]

Batches:  40%|███▉      | 70/176 [01:18<01:29,  1.19it/s]

Batches:  40%|████      | 71/176 [01:19<01:27,  1.20it/s]

Batches:  41%|████      | 72/176 [01:20<01:27,  1.19it/s]

Batches:  41%|████▏     | 73/176 [01:21<01:25,  1.20it/s]

Batches:  42%|████▏     | 74/176 [01:21<01:24,  1.21it/s]

Batches:  43%|████▎     | 75/176 [01:22<01:22,  1.22it/s]

Batches:  43%|████▎     | 76/176 [01:23<01:21,  1.22it/s]

Batches:  44%|████▍     | 77/176 [01:24<01:20,  1.23it/s]

Batches:  44%|████▍     | 78/176 [01:25<01:20,  1.22it/s]

Batches:  45%|████▍     | 79/176 [01:25<01:19,  1.22it/s]

Batches:  45%|████▌     | 80/176 [01:26<01:16,  1.25it/s]

Batches:  46%|████▌     | 81/176 [01:27<01:16,  1.25it/s]

Batches:  47%|████▋     | 82/176 [01:28<01:15,  1.25it/s]

Batches:  47%|████▋     | 83/176 [01:29<01:13,  1.27it/s]

Batches:  48%|████▊     | 84/176 [01:29<01:11,  1.29it/s]

Batches:  48%|████▊     | 85/176 [01:30<01:10,  1.30it/s]

Batches:  49%|████▉     | 86/176 [01:31<01:09,  1.30it/s]

Batches:  49%|████▉     | 87/176 [01:32<01:07,  1.32it/s]

Batches:  50%|█████     | 88/176 [01:32<01:06,  1.33it/s]

Batches:  51%|█████     | 89/176 [01:33<01:04,  1.36it/s]

Batches:  51%|█████     | 90/176 [01:34<01:02,  1.38it/s]

Batches:  52%|█████▏    | 91/176 [01:34<01:00,  1.40it/s]

Batches:  52%|█████▏    | 92/176 [01:35<01:02,  1.34it/s]

Batches:  53%|█████▎    | 93/176 [01:36<01:00,  1.36it/s]

Batches:  53%|█████▎    | 94/176 [01:37<01:00,  1.37it/s]

Batches:  54%|█████▍    | 95/176 [01:37<01:00,  1.34it/s]

Batches:  55%|█████▍    | 96/176 [01:38<00:58,  1.36it/s]

Batches:  55%|█████▌    | 97/176 [01:39<00:57,  1.37it/s]

Batches:  56%|█████▌    | 98/176 [01:40<00:56,  1.38it/s]

Batches:  56%|█████▋    | 99/176 [01:40<00:55,  1.38it/s]

Batches:  57%|█████▋    | 100/176 [01:41<00:54,  1.40it/s]

Batches:  57%|█████▋    | 101/176 [01:42<00:53,  1.40it/s]

Batches:  58%|█████▊    | 102/176 [01:42<00:52,  1.40it/s]

Batches:  59%|█████▊    | 103/176 [01:43<00:50,  1.43it/s]

Batches:  59%|█████▉    | 104/176 [01:44<00:49,  1.45it/s]

Batches:  60%|█████▉    | 105/176 [01:44<00:48,  1.46it/s]

Batches:  60%|██████    | 106/176 [01:45<00:48,  1.45it/s]

Batches:  61%|██████    | 107/176 [01:46<00:47,  1.45it/s]

Batches:  61%|██████▏   | 108/176 [01:47<00:46,  1.45it/s]

Batches:  62%|██████▏   | 109/176 [01:47<00:46,  1.44it/s]

Batches:  62%|██████▎   | 110/176 [01:48<00:44,  1.47it/s]

Batches:  63%|██████▎   | 111/176 [01:49<00:44,  1.46it/s]

Batches:  64%|██████▎   | 112/176 [01:49<00:42,  1.50it/s]

Batches:  64%|██████▍   | 113/176 [01:50<00:41,  1.52it/s]

Batches:  65%|██████▍   | 114/176 [01:51<00:41,  1.51it/s]

Batches:  65%|██████▌   | 115/176 [01:51<00:40,  1.51it/s]

Batches:  66%|██████▌   | 116/176 [01:52<00:39,  1.51it/s]

Batches:  66%|██████▋   | 117/176 [01:53<00:39,  1.51it/s]

Batches:  67%|██████▋   | 118/176 [01:53<00:37,  1.56it/s]

Batches:  68%|██████▊   | 119/176 [01:54<00:36,  1.58it/s]

Batches:  68%|██████▊   | 120/176 [01:54<00:35,  1.59it/s]

Batches:  69%|██████▉   | 121/176 [01:55<00:34,  1.60it/s]

Batches:  69%|██████▉   | 122/176 [01:56<00:33,  1.59it/s]

Batches:  70%|██████▉   | 123/176 [01:56<00:32,  1.63it/s]

Batches:  70%|███████   | 124/176 [01:57<00:31,  1.66it/s]

Batches:  71%|███████   | 125/176 [01:57<00:31,  1.64it/s]

Batches:  72%|███████▏  | 126/176 [01:58<00:30,  1.64it/s]

Batches:  72%|███████▏  | 127/176 [01:59<00:29,  1.65it/s]

Batches:  73%|███████▎  | 128/176 [01:59<00:29,  1.61it/s]

Batches:  73%|███████▎  | 129/176 [02:00<00:29,  1.61it/s]

Batches:  74%|███████▍  | 130/176 [02:00<00:28,  1.59it/s]

Batches:  74%|███████▍  | 131/176 [02:01<00:28,  1.60it/s]

Batches:  75%|███████▌  | 132/176 [02:02<00:27,  1.62it/s]

Batches:  76%|███████▌  | 133/176 [02:02<00:26,  1.64it/s]

Batches:  76%|███████▌  | 134/176 [02:03<00:25,  1.66it/s]

Batches:  77%|███████▋  | 135/176 [02:03<00:23,  1.71it/s]

Batches:  77%|███████▋  | 136/176 [02:04<00:23,  1.71it/s]

Batches:  78%|███████▊  | 137/176 [02:05<00:22,  1.76it/s]

Batches:  78%|███████▊  | 138/176 [02:05<00:21,  1.73it/s]

Batches:  79%|███████▉  | 139/176 [02:06<00:21,  1.75it/s]

Batches:  80%|███████▉  | 140/176 [02:06<00:19,  1.81it/s]

Batches:  80%|████████  | 141/176 [02:07<00:20,  1.71it/s]

Batches:  81%|████████  | 142/176 [02:07<00:19,  1.70it/s]

Batches:  81%|████████▏ | 143/176 [02:08<00:19,  1.72it/s]

Batches:  82%|████████▏ | 144/176 [02:09<00:17,  1.80it/s]

Batches:  82%|████████▏ | 145/176 [02:09<00:17,  1.80it/s]

Batches:  83%|████████▎ | 146/176 [02:10<00:16,  1.83it/s]

Batches:  84%|████████▎ | 147/176 [02:10<00:15,  1.87it/s]

Batches:  84%|████████▍ | 148/176 [02:11<00:14,  1.88it/s]

Batches:  85%|████████▍ | 149/176 [02:11<00:14,  1.89it/s]

Batches:  85%|████████▌ | 150/176 [02:12<00:13,  1.95it/s]

Batches:  86%|████████▌ | 151/176 [02:12<00:12,  1.96it/s]

Batches:  86%|████████▋ | 152/176 [02:13<00:12,  1.92it/s]

Batches:  87%|████████▋ | 153/176 [02:13<00:11,  1.95it/s]

Batches:  88%|████████▊ | 154/176 [02:14<00:11,  1.93it/s]

Batches:  88%|████████▊ | 155/176 [02:14<00:10,  2.03it/s]

Batches:  89%|████████▊ | 156/176 [02:15<00:09,  2.06it/s]

Batches:  89%|████████▉ | 157/176 [02:15<00:09,  2.05it/s]

Batches:  90%|████████▉ | 158/176 [02:16<00:08,  2.05it/s]

Batches:  90%|█████████ | 159/176 [02:16<00:08,  2.10it/s]

Batches:  91%|█████████ | 160/176 [02:16<00:07,  2.14it/s]

Batches:  91%|█████████▏| 161/176 [02:17<00:06,  2.22it/s]

Batches:  92%|█████████▏| 162/176 [02:17<00:06,  2.25it/s]

Batches:  93%|█████████▎| 163/176 [02:18<00:05,  2.35it/s]

Batches:  93%|█████████▎| 164/176 [02:18<00:04,  2.41it/s]

Batches:  94%|█████████▍| 165/176 [02:18<00:04,  2.49it/s]

Batches:  94%|█████████▍| 166/176 [02:19<00:03,  2.56it/s]

Batches:  95%|█████████▍| 167/176 [02:19<00:03,  2.62it/s]

Batches:  95%|█████████▌| 168/176 [02:20<00:02,  2.67it/s]

Batches:  96%|█████████▌| 169/176 [02:20<00:02,  2.73it/s]

Batches:  97%|█████████▋| 170/176 [02:20<00:02,  2.75it/s]

Batches:  97%|█████████▋| 171/176 [02:21<00:01,  2.91it/s]

Batches:  98%|█████████▊| 172/176 [02:21<00:01,  2.88it/s]

Batches:  98%|█████████▊| 173/176 [02:21<00:00,  3.07it/s]

Batches:  99%|█████████▉| 174/176 [02:22<00:00,  3.05it/s]

Batches:  99%|█████████▉| 175/176 [02:22<00:00,  3.21it/s]

Batches: 100%|██████████| 176/176 [02:22<00:00,  3.73it/s]

Batches: 100%|██████████| 176/176 [02:22<00:00,  1.24it/s]

pt.Experiment:   0%|          | 0/2 [00:00<?, ?system/s]

pt.Experiment:  50%|█████     | 1/2 [00:00<00:00,  2.17system/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:00<00:00, 119.04it/s]

pt.Experiment: 100%|██████████| 2/2 [00:00<00:00,  3.81system/s]

                                         name  nDCG@50   MRR@50  Prec@50  Recall@50    F1@50   MAP@50
                                 ANN@100->@50 0.500596 0.794444 0.462667   0.411309 0.435479 0.273427
OpenSearch sparse encoder (multilingual)->@50 0.305359 0.713445 0.282667   0.180631 0.220413 0.112571

,name,nDCG@50,MRR@50,Prec@50,Recall@50,F1@50,MAP@50
0,ANN@100->@50,0.500596,0.794444,0.462667,0.411309,0.435479,0.273427
1,OpenSearch sparse encoder (multilingual)->@50,0.305359,0.713445,0.282667,0.180631,0.220413,0.112571

In [5]:
table1_df = to_table1_style(metrics_df, ann_name="ANN@100->@50", k_eval=FINAL_TOPK)
table1_df = table1_df.sort_values("nDCG", ascending=False).reset_index(drop=True)

for col in ["nDCG", "Delta", "%", "MRR", "P", "R", "F1", "MAP"]:
    table1_df[col] = table1_df[col].astype(float)

table1_df.to_csv(ART_DIR / "sparse_baseline_table1_style.csv", index=False)
metrics_df.to_csv(ART_DIR / "sparse_baseline_metrics_raw.csv", index=False)

print(table1_df.to_string(index=False))
table1_df

                                       Method     nDCG     Delta         %      MRR        P        R       F1      MAP
                                 ANN@100->@50 0.500596  0.000000   0.00000 0.794444 0.462667 0.411309 0.435479 0.273427
OpenSearch sparse encoder (multilingual)->@50 0.305359 -0.195237 -39.00085 0.713445 0.282667 0.180631 0.220413 0.112571

,Method,nDCG,Delta,%,MRR,P,R,F1,MAP
0,ANN@100->@50,0.500596,0.000000,0.00000,0.794444,0.462667,0.411309,0.435479,0.273427
1,OpenSearch sparse encoder (multilingual)->@50,0.305359,-0.195237,-39.00085,0.713445,0.282667,0.180631,0.220413,0.112571